name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install build dependencies
        run: sudo apt update && sudo apt install -y build-essential python3

      - name: Install app dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun typecheck

      - name: Lint
        run: bun lint

      - name: Build
        run: bun run build